---
title: "{{{title}}}"
author: {{{author}}}
output:
  packagedocs:
    toc: true
    css: menu-fix.css{{{navpills}}}
extra_credits: and <a href='https://github.com/hafen/datasummary'>datasummary</a>
---


```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(rbokeh)
library(knitr)
load("{{{di_path}}}")
```

{{{intro_rmd}}}


```{r echo=FALSE, results='asis'}
if(!is.null(di$meta)) {
  nms <- names(di$meta)
  tmpdf <- data.frame(
    v1 = gsub("_", " ", nms),
    v2 = unname(unlist(di$meta)))

  txt <- c("# Meta #", "",
    "|  property  |  value  |",
    "| ---------- | ------- |",
    apply(tmpdf, 1, function(x) {
      paste("|", paste(x, collapse = " | "), "|")}))

  cat(paste(txt, collapse = "\n"))
}
```

# Data #

There are `r di$nrow` records for `r di$ncol` variables.

A sample of the data:

```{r echo=FALSE}
DT::datatable(di$head, rownames = FALSE)
```

# Missing Values #

```{r echo=FALSE, message=FALSE}
plot_missing(di)
```

<!--

```{r echo=FALSE, results='asis'}
vartab <- data.frame(variable = names(di$var_summ), type = unname(sapply(di$var_summ, function(x) x$type)))
knitr::kable(vartab)
```
-->

```{r echo=FALSE, results='asis'}
txt <- ""
if(length(di$na_cols) > 0 || length(di$dups) > 0)
  txt <- "# Notes #\n\n"

if(length(di$na_cols) > 0)
 txt <- c(paste0("The following variables are all NA: `",
  paste0(names(di$na_cols), collapse = "`, `"), "`"), "")

if(length(di$dups) > 0) {
  txt <- c(txt, "The following variables are duplicates:", "",
    sapply(di$dups, function(x) {
      paste0("- `", paste0(x, collapse = "`, `"), "`")
    }), "")

cat(paste(txt, collapse = "\n"))
}
```

{{{var_summaries}}}


{{{post_rmd}}}
